'use client'

import { SOCIAL_ICONS as SERVER_SOCIALS, ALL_TECHS as SERVER_TECHS, ROUTES as SERVER_ROUTES, FALLBACK_IMG as SERVER_FALLBACK_IMG } from "./constants"

export const SOCIAL_ICONS = SERVER_SOCIALS
export const ALL_TECHS = SERVER_TECHS
export const ROUTES = SERVER_ROUTES
export const FALLBACK_IMG = SERVER_FALLBACK_IMG
