export const TECH_STACK_DATA = [
  { name: "Adobe Illustrator", value: "ai" },
  { name: "Adobe Photoshop", value: "ps" },
  { name: "Autodesk 3DS MAX", value: "3dsmax" },
  { name: "Bootstrap", value: "bootstrap" },
  { name: "Claude Code", value: "claudecode" },
  { name: "Cloudinary", value: "cloudinary" },
  { name: "CorelDraw", value: "coreldraw" },
  { name: "CSS", value: "css" },
  { name: "Emotion", value: "emotioncss" },
  { name: "Express", value: "express" },
  { name: "Figma", value: "figma" },
  { name: "Firebase", value: "firebase" },
  { name: "Git", value: "git" },
  { name: "Github", value: "github" },
  { name: "Github Copilot", value: "copilot" },
  { name: "Gitlab", value: "gitlab" },
  { name: "HTML", value: "html" },
  { name: "Inertia Rails", value: "inertiarails" },
  { name: "JavaScript", value: "javascript" },
  { name: "Jest", value: "jest" },
  { name: "Ladle", value: "ladle" },
  { name: "MySQL", value: "mysql" },
  { name: "Neon", value: "neon" },
  { name: "Next.js", value: "nextjs" },
  { name: "Node.js", value: "node" },
  { name: "Playwright", value: "playwright" },
  { name: "PostgreSQL", value: "postgresql" },
  { name: "Prisma", value: "prisma" },
  { name: "React", value: "react" },
  { name: "React Native", value: "reactnative" },
  { name: "React Testing Library", value: "rtl" },
  { name: "Rhinoceros", value: "rhinoceros" },
  { name: "Ruby", value: "ruby" },
  { name: "Ruby on Rails", value: "rubyonrails" },
  { name: "Sass", value: "sass" },
  { name: "Shadcn/ui", value: "shadcnui" },
  { name: "SolidWorks", value: "solidworks" },
  { name: "SQL", value: "sql" },
  { name: "SQLite", value: "sqlite" },
  { name: "Storybook", value: "storybook" },
  { name: "Styled Components", value: "styledcomponents" },
  { name: "Supabase", value: "supabase" },
  { name: "Tailwind", value: "tailwind" },
  { name: "Turborepo", value: "turborepo" },
  { name: "Typescript", value: "typescript" },
  { name: "Vercel", value: "vercel" },
  { name: "Vite", value: "vite" },
  { name: "Vitest", value: "vitest" },
  { name: "V-Ray", value: "vray" },
];
