import { SVGProps } from "react";

type SpriteIconProps = SVGProps<SVGSVGElement> & {
  /** Sprite filename under /public, e.g. "techs-sprite.svg". */
  sprite: string;
  /** Symbol id inside the sprite. */
  name: string;
};

// Renders an icon by referencing an external SVG sprite via <use>. Keeps the
// heavy path data out of the server-rendered HTML: each sprite is fetched once
// and cached, instead of inlining SVG markup on every page render.
// Sprites are generated by scripts/generate-icon-sprite.mts (`pnpm icons:sprite`).
function SpriteIcon({ sprite, name, ...props }: SpriteIconProps) {
  return (
    <svg {...props}>
      <use href={`/${sprite}#${name}`} />
    </svg>
  );
}

export default SpriteIcon;
