import { writeFileSync } from "node:fs";
import { createElement } from "react";

import { renderToStaticMarkup } from "react-dom/server";
import { optimize, type Config } from "svgo";

import * as Companies from "../src/icons/companies/index";
import * as Hobbies from "../src/icons/hobbies/index";
import * as Jobs from "../src/icons/jobs/index";
import * as Techs from "../src/icons/techs/index";

type IconComponent = (props: Record<string, unknown>) => unknown;
type IconModule = Record<string, IconComponent>;

type SpriteSpec = {
  file: string;
  // tsx/esbuild CJS interop nests re-exported barrels under `.default`.
  modules: Record<string, unknown>[];
  // Emit a <name, {width,height}> map so consumers can size the outer <svg>.
  // Needed for logos with varied aspect ratios that rely on intrinsic size.
  dimensionsFile?: string;
};

const SPRITES: SpriteSpec[] = [
  { file: "public/techs-sprite.svg", modules: [Techs] },
  {
    file: "public/about-sprite.svg",
    modules: [Companies, Jobs, Hobbies],
    dimensionsFile: "src/icons/about-sprite-dimensions.ts",
  },
];

// Per-icon SVGO config. `prefix` MUST be unique per icon so internal ids
// (many icons ship a clipPath id="a") don't collide once merged into one sprite.
// - floatPrecision: 2  -> trims the biggest cost, over-precise path coordinates.
// - convertColors.currentColor -> single monochrome sprite recolored via CSS `color`.
function svgoConfig(prefix: string): Config {
  return {
    multipass: true,
    floatPrecision: 2,
    plugins: [
      {
        name: "preset-default",
        params: { overrides: { convertColors: { currentColor: true } } },
      },
      { name: "prefixIds", params: { prefix, delim: "-" } },
      "removeDimensions",
    ],
  };
}

// Structural attrs live on <svg> but must not survive onto <symbol>; everything
// else (fill, stroke, stroke-width, fill-rule…) is presentation and is inherited
// by <use>, so it must be preserved — many icons set fill on the root, not paths.
const STRUCTURAL_ATTRS = new Set([
  "xmlns", "xmlns:xlink", "width", "height", "viewbox", "class", "style",
  "version", "id", "role", "tabindex", "x", "y", "aria-hidden", "aria-label",
]);

function extractRootAttrs(rawAttrs: string): { viewBox?: string; presentation: string } {
  const attrs = [...rawAttrs.matchAll(/([a-zA-Z:-]+)="([^"]*)"/g)];
  let viewBox: string | undefined;
  const presentation: string[] = [];

  for (const [, key, value] of attrs) {
    const lower = key.toLowerCase();
    if (lower === "viewbox") {
      viewBox = value;
    } else if (!STRUCTURAL_ATTRS.has(lower)) {
      presentation.push(`${key}="${value}"`);
    }
  }

  return { viewBox, presentation: presentation.length ? " " + presentation.join(" ") : "" };
}

type Built = { symbol: string; name: string; width: number; height: number };

function buildSymbol(name: string, Component: IconComponent): Built {
  const raw = renderToStaticMarkup(createElement(Component as never));
  const optimized = optimize(raw, svgoConfig(name)).data;

  const match = optimized.match(/<svg([^>]*)>([\s\S]*)<\/svg>/);
  if (!match) {
    throw new Error(`Could not parse SVG output for icon "${name}"`);
  }
  const { viewBox, presentation } = extractRootAttrs(match[1]);
  if (!viewBox) {
    throw new Error(`Icon "${name}" has no viewBox`);
  }
  const [, , w, h] = viewBox.split(/\s+/).map(Number);

  return {
    symbol: `  <symbol id="${name}" viewBox="${viewBox}"${presentation}>${match[2].trim()}</symbol>`,
    name,
    width: w,
    height: h,
  };
}

for (const spec of SPRITES) {
  const seen = new Set<string>();
  const built: Built[] = [];

  for (const mod of spec.modules) {
    const icons = ((mod as Record<string, unknown>).default ?? mod) as IconModule;
    for (const [name, Component] of Object.entries(icons)) {
      if (typeof Component !== "function") continue;
      if (seen.has(name)) {
        throw new Error(`Duplicate icon name "${name}" in ${spec.file}; prefix by folder`);
      }
      seen.add(name);
      built.push(buildSymbol(name, Component));
    }
  }

  const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
${built.map((b) => b.symbol).join("\n")}
</svg>
`;
  writeFileSync(spec.file, sprite);

  if (spec.dimensionsFile) {
    const entries = built
      .map((b) => `  ${b.name}: { width: ${b.width}, height: ${b.height} },`)
      .join("\n");
    const ts = `// AUTO-GENERATED by scripts/generate-icon-sprite.mts — do not edit.
export const ABOUT_ICON_DIMENSIONS: Record<string, { width: number; height: number }> = {
${entries}
};
`;
    writeFileSync(spec.dimensionsFile, ts);
  }

  console.log(`Generated ${spec.file} with ${built.length} symbols.`);
}
